services:
  - type: web
    name: codereviewer-app
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: codereviewer-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

  - type: pserv
    name: codereviewer-db
    env: postgresql
    plan: free
    ipAllowList: [] 