"""Add detected_language column to CodeSubmission

Revision ID: 048e904c317e
Revises: 058012a1db8c
Create Date: 2025-07-13 11:13:47.252916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048e904c317e'
down_revision = '058012a1db8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_language', sa.String(length=20), nullable=True))
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('tags')
        batch_op.drop_column('duplicate_patterns')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('code_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplicate_patterns', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.alter_column('language',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.drop_column('detected_language')

    # ### end Alembic commands ###
